dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: P8PwduorsbAwJp0KbYxMUw2lD7HsJd8nNZzVNAnVVgUisIwXkSWY0zlFKfOKaJfz1TBRWlVYUAyU0oHdInr1JasoBTuyxphR/Sd+Z60SKP5RU++TdAmD4YQCfG0rJ7t2lQCDHRdgfTPS9wNIjUqscS92NXFdorTu/5YGg38Gk64c8Il1KqdKWysPBsM51HHv+PuMBXinfCkp7wrYuYJjOAjbzeSoDu4//yZj9p3ifmwQdYsZFTeX40S4wg/dkAl0/AhrBQ10jfLTAQgXOXcrAQifIP1z2VJVw5xwzL5OduoddDzVlKKnJ93PHnkvLCgqzXh0VAgcMp7iYVvaf+XCyKAuDLi8Y30dScyyBszT3qf58VcmfE2oQna76on2jMKSw9wgqVwaLEY0b4k1PrUCUeQs5Z8MpP4ZrJ96qKjizGOGhjtybEupaUTvPe/JDwOmJwzsKJUq/atylS3QO0rXhqlRo3Y87+YmXrgaFgLcDXgXlGpmfwLq/1LdFcBWTS8QNFvSBosRDJqHURYpvM0AGitciBgIHtMn56jrgbVfuj085Od/FLnzTpAAEg0Ik2xgwOeM1dIGmi8M/Oeky+cnL0/57Cx8W2JhLg8hWvvlCLVw+0o9Gs+Q12pWYgdNHE2hXi0Xcr+rMNqmhV7g7PGqNio5FJgukwg8vvGO2wEGD3U=
