dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: e3CKKSYQ3C2A0EyHtm8ihEB3qa7GL/m6zrB/qR1CFmBzvn0bgytURVZaoJ5AyeExIKYYKugE+K6DHNRYIXhwa+yqXyb3hoA7joxVjHRQgyM1X3enkBT4uLSFIv9Zw/TrVPCVYo37q9uGdMCi0sSzT/ZvwGqIVHKuSaDTS1qX1fSyJTHhTQZFYahv6OV971IJqnja2sITEM2uz6QbSu6GSPYQTrJLsVwTyIXTCgwB0vqL0LmN16TTfcIndEUwn9GzJADVn3Fri9wmXUpn/h7vFJ+o/ONO2RylV7Pv2o6Kd+oaafwABhl6Ca2E2p+XyHv937XH+JMrEyVS64hgXPpipcoy+v/PQyLv4qQ8WPD7hjwp4AeNLvqSCfrXz0/zDZR0yidGooTi+ahU2TQYcLaDCbvAR1OJnD4Jx2EPRM3/9P2++sx/g6BuLSixFcYbxFdpjvlfpnFqq6z8FzQIi+xSAw8EUqy4aOi8/os/sccfdegkBz63SZi2jSsW6H7+ZOdCWqh3aV8vYkTs4qeR3A9QkD3VyBX88ZiuHbPtdiCs4ni2cpEP/qQ08rSNzQfCDb+5p7PIkQdyBpLfZjYv2zuyBIERe0oCpn8TA3/MajOGC44Gf1s6RuUt1nBsmDuXLElK+4Ra7jZDvY0vnLdocEHRjbIIBLcVwJfKtYVJ9alk2cM=
