dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Lznp+MY28A6tpbHNpSeJXRDyKPTlphda/tkIECVOqMJu0xePkAHeG5wH9F2bG7gBOa/3z7DQkX/MWVtvZ3q3YcieKjJjFDP4M/LZjMrarqMoJ4ec0iux5WLDNJrC4/5RgV263pJZL4GDp4VYIAM8QoEfdQyd4Ck3ZY719tWU++TFioih7k4mhlAPYffPbzclK7FkOkD3h0W5a7PJgoFzhyCut2VHK/vSu5VL3r8AcshVuGI1p8fpVLNe4P6fcvPhXkW2vcmh6JdsWhSHe734KhC1yjWpUJULG7RxSCOsl/CREuCTN3lJYA8YDjGSBYqB6C5HlVNIfsbmVepIqz4KBMQWA9PQhY1VIytWapsoCtXP9cSwu/Zsqk5ApiAeCqsioRiBw3IyeUjWn3VHOgI0DrKCztExO2WuJx6PbdBNggKwut3kPRARM0QACRJ6ZqZeuLS5Mq/tji+Ex5kJ2YmYEiSFDWx8aCqsUqgY0Qr3eQvxwtTrJQirfykdXTgGAd+MNw6ZIEN0ctqHaKhIQ2EsVHYqMVcUDEaL/k2KpbFNDb78RCVs3Gc3uPrQhP4F2HX58Xew26zKmBM3YjCGapogrc1KJtxNr7+T2w72Q4OL0rPqOLk74BoU1N40XQDGymNx9ZSlgNoCJdKhkPSD2fDYMVMJ3i5f8owg62afqCmG3B4=
