dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    secure: kcDPzX81Nd7trrwMx177OZtTECaTwbvNLuu4JZMWfuNXeX2/pt7JDYsM73MFOPnq805Lu2M6V66ZjvwPXd9wX0ywM6UMMHZ2sdc4nCPM8mI5/GT8lX4oBw895XN7GJdRXDu0ELCSMjnqVP3M/qS38TVULgzZuhZI9lr54qtFYy92l5ROQ8Thx7KUUYtPy3kZCnJ8D+pBf9YE9Y2muoFxp0zLe20qkB6akUoI6Z0OWhELqNKryDGuTiB/JFfRr5uLgKTzrwd7GwkjgmTZeniFMQqX8VWdtuIiWhWG6yBblJcgaeZlbsPdAP8Xmi9iT1x2+TK3j0F8m4NgmR5ZJRJwtAnx8KG6Oor2pYWAcawsmUeRLbB05kdhD818d/UWSU2nsyhxNBcgIHj+1YDpHWtRTCPBWDnJIeS/NeWFAGpgdclm2ulH74PGYeuOrN8DgIT17fKWEHg7VNBQbaGPQT04cN3eZleNPfh85INAYQJ1Hiq7sG60KKRBWv0KFbfAK5iABwVOkNWMduklRsPGlVr4JYvh8HYaW8jzZ5xhw5ieLgB+BSvoXFBYNxmwUovVJS9LieEg8tFRTG+QrYLXjFfaSAZ9iOo2nPqoHCwI2bQGA1SukOaofSb9UuFRbf1B0sfAg8aoVfldPM2sjPN0Fd6hHtocFPbtJIf71qIjuo03YX0=
