dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: FQfPavDN7KTOItf4x5pubxXiS72mweUSwV+/gduDssjuakJJVcWgCsYTUeqhmtaLLa9OKvJHVPZZcpRdeGZMfFLkLE4O4fujplz1tW6KpgcHpc/kPVSUkYz6XKDKvBx+jbm+PmVvUkl2/uKwSYBjnOMYVYAysbCtl+DCIQk+hQjHh0zhsLMMucd3E/42lMeYajRbX6FMWQzg+AwdxDO5EvaCtSGBnZE8tk8HgfPodkUIdYirXK2iNu+q2SBR/5tAy3WJhAx+9gfIs6J7xI8kSsrulpO+GXA7khPqFgLoe1jU/TzexTHLTOvVqZYU+AEBAI2z/jr3RN5tB2miF/+aa3RmZk6EHHq74UgUmgUIBJw5S473C6hZUpMiYDfmH1FOi+noQq+a7jsS0wJ/WTkblRXTXiqz8eGcIK5wHziYYdfdM58BgW9Pn/2NWebYk5RIRpqFKJtWwigtVJCpmzDBjLURKhxuoZrwe4ghk/Vm2GHII+8R20Y72hZeJ/3XiiehdTPiGc1Kyc/Ug0Vz89CBE5h1C8tJ8of6sszvYDuvLBzNULwZpEc6NCt0P28TsrdX7c9qj5K6txSNhdrMT7vyTrzN7KwizcI+rJHBKvfkFdglo8/wKAbLpsr2nx73Ks2m02E6Y4Y5cQU7I3Y2+f3WZL0jDXgrOjnRo7Cj4zD16PY=
